### ISSUE TITLE
Expose metrics endpoint

### ISSUE THREAD

**Issue by mirekys** [cs3org/charts#8]
To expose the `/metrics` endpoint for Prometheus, a `[http.services.prometheus]` service needs to be added to the IOP config map, e.g. to `gateway.toml`

**Comment by SamuAlfageme** [comment]
Closing as discussed. We now enable `[http.services.prometheus]` by default since https://github.com/cs3org/charts/pull/7 in:

https://github.com/cs3org/charts/blob/a050a7488635204f15902e95e65168b6d3800656/revad/values.yaml#L28
